### PR TITLE
Fix hasMore not fetching datastore cursor

### LINKED ISSUE #57: Bug in runQuery sample code
Hello!!

I've been having some problems with the queries in datastore and I found the reason. 
It's just this line of code

```
var hasMore = entities.length === limit ? nextQuery.startVal : false;
```

This fails if the entities given are the last ones. The condition is true but then nextQuery doesn't exist.

I think it should be better in this way.
```
// same qty or no more
var hasMore = false;
if(entities.length === limit && nextQuery)
  hasMore = nextQuery.startVal;
```

### PR DESCRIPTION
**Pull request by ace-n**
Fixes #57 

@jonparrott @jmdobry Care to review?

### CODE REVIEW

File: 2-structured-data/books/model-datastore.js [hunk 1]
```diff
@@ -98,7 +98,7 @@ function list (limit, token, cb) {
     if (err) {
       return cb(err);
     }
-    var hasMore = entities.length === limit ? nextQuery.startVal : false;
+    var hasMore = nextQuery.moreResults === 'MORE_RESULTS_AFTER_LIMIT' ? nextQuery.endCursor : false;
```
Comment (jonparrott) [inline 2-structured-data/books/model-datastore.js]: Magic string? Does the client library not have a constant for this?

Comment (jmdobry) [inline 2-structured-data/books/model-datastore.js]: It does, this should be changed to:

```js
var hasMore = nextQuery.moreResults === datastore.MORE_RESULTS_AFTER_CURSOR ? nextQuery.endCursor : false;
```

**Comment by ace-n** [comment]
@dpebot Merge when green
